version: '3.9'

services:
  nginx:
    image: nginx
    container_name: nginx-reverse-proxy
    ports:
      - "80:80" # Expose Nginx to the internet
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:rw
